Repository yarion1/Front-Ps, pull requests merged in 2022-05, with the labels that each got.

#16 Homepage/it03/r28
  src/App.js
  src/assets/img/logo-useit.png
  src/assets/img/wave.png
  src/assets/styles/Navbar/stylednavbar.js
  src/components/Navbar/index.js
  src/pages/Home/Home.js
  src/pages/Home/styledhomepage.js
Labels: bug

#24 subindo listagem de alugueis e refenciando rota da navbar para lista …
  package.json
  src/App.js
  src/components/Navbar/index.js
  src/pages/Lista/Lista.js
  src/pages/Lista/style.css
  src/pages/rent/listRent.js
  src/pages/rent/rent.css
  src/pages/rent/styledrent.js
Labels: enhancement

#27 Develop
  src/components/Modal/Modalmoney.js
  src/components/Modal/Modalpix.js
  src/components/Modal/Styledmodalbuy.js
  src/components/Modal/Styledmodalinfopayment.js
  src/components/Modal/Styledmodalpayment.js
  src/pages/Lista/Lista.js
Labels: release

#28 Bug-fix
  src/App.js
  src/assets/styles/Navbar/stylednavbar.js
  src/components/Navbar/index.js
  src/components/PreLoader/PreLoader.js
  src/components/ProductInspect/ProductInspect.js
  src/components/ProductInspect/StyledProductInspect.js
  src/components/SignUpForm/signUpForm.js
  src/pages/Equipment/EquipmentDetail/EquipamentDetailInfo.js
  src/pages/Equipment/EquipmentDetail/EquipmentDetail.js
  src/pages/Equipment/EquipmentDetail/StyledEquipmentDetail.js
  src/pages/Equipment/EquipmentSecurity/EquipmentSecurity.js
  src/pages/Equipment/EquipmentTecnicalDetail/EquipmentTecnicalDetail.js
  src/pages/Login/Login.js
Labels: bug

#30 implementacao do modal de avaliacao
  src/assets/StarRating/StarRating.js
  src/assets/StarRating/StyledStar.js
  src/components/Modal/ModalAv.js
  src/components/Modal/StyledModalAv.js
  src/pages/Equipment/EquipmentDetail/EquipmentDetail.js
  src/pages/Equipment/EquipmentDetail/StyledEquipmentDetail.js
Labels: enhancement

#31 PreenchimentoDados/IT04/R41
  package.json
  src/App.js
  src/assets/styles/auth/authstyled.js
  src/components/Mask/mask.js
  src/components/SignUpForm/signUpForm.js
  src/pages/SignUp/DadosCadastrais/DadosCadastrais.js
  src/pages/SignUp/DadosCadastrais/StyledDadosCadastrais.js
Labels: enhancement

#33 Sidebar/IT04/R42
  package.json
  src/App.js
  src/assets/styles/Sidebar/StyledSidebar.css
  src/components/Sidebar/SidebarUser.js
  src/components/SignUpForm/signUpForm.js
  src/pages/SignUp/DadosCadastrais/DadosCadastrais.js
  src/pages/User_profile/user_profile.js
  src/pages/rent/listRent.js
Labels: enhancement
